# Generated by Django 4.1.2 on 2022-11-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetail',
            name='date',
            field=models.DateField(),
        ),
    ]
