# Generated by Django 4.1.2 on 2025-02-21 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_alter_appointmentdetail_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medicine',
        ),
    ]
