# Generated by Django 4.1.2 on 2022-10-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='study',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
